dataset<-read.table("household_power_consumption.txt", head=TRUE, sep=";")
dataset$datetime <- strptime(paste(dataset$Date, dataset$Time), format="%d/%m/%Y %H:%M:%S")
dataset[,1] <- as.Date(dataset$Date, "%d/%m/%Y")
temp <- subset(dataset, as.Date(Date) >= '2007-02-01' & as.Date(Date) <= '2007-02-02')
temp[,7] <- as.character(temp[,7])
temp[,7] <- as.numeric(temp[,7])
temp[,8] <- as.character(temp[,8])
temp[,8] <- as.numeric(temp[,8])
temp[,9] <- as.character(temp[,9])
temp[,9] <- as.numeric(temp[,9])

png(filename="plot3.png", width=480, height=480)
plot(temp$datetime, temp$Sub_metering_1, type="l", xlab = "",ylab = "",axes=FALSE, col = "black", ylim=c(0,38))
axis(2,ylim=c(0,38), col="black")
mtext("Energy sub metering",side=2, line=2.5)
box()
par(new=TRUE)
plot(temp$datetime, temp$Sub_metering_2, type="l", xlab = "",ylab = "",axes=FALSE, col = "red", ylim=c(0,38))
par(new=TRUE)
plot(temp$datetime, temp$Sub_metering_3, type="l", xlab = "",ylab = "", col = "blue", ylim=c(0,38))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), text.col="black",lty="solid", col=c("black", "red","blue"))
dev.off()